#!/bin/sh /etc/rc.common
#
# Copyright (C) 2013 Gerrit 'Nold' Pannek
#

START=99

start() {
	echo -n "Starting SHIPS... "
	
	FAILLOG=$(grep "^FAILLOG=" /etc/ships/ships.conf | head -1 | cut -f2 -d"=")
	LOCKFILE=$(grep "^LOCKFILE=" /etc/ships/ships.conf | head -1 | cut -f2 -d"=")
	
	if [ -f $LOCKFILE ] ; then
		echo
		echo "Lockfile $LOCKFILE exists. Can't continue."
		exit 1
	fi
	
	test -d $(dirname $FAILLOG) || mkdir -p $(dirname $FAILLOG)
	echo -n > $FAILLOG || exit 1
	
	/usr/bin/ships.sh &> /dev/null &
	echo $! > $LOCKFILE
	
	echo "done"
	exit 0
}

stop() {
	echo -n "Stopping SHIPS... "
	LOCKFILE=$(grep "^LOCKFILE=" /etc/ships/ships.conf | head -1 | cut -f2 -d"=")
	if [ -f $LOCKFILE ] ; then
		kill $(cat $LOCKFILE) 2>/dev/null
		rm -f $LOCKFILE
		sleep 2
		#just to make sure.. but ships should quit clean
		killall -9 ships.sh 2>/dev/null
	fi

	for pidfile in $(ls -1 /var/run/ships_jail_*_logread.pid); do
		kill -9 $(cat $pidfile) 2> /dev/null && rm $pidfile 2>/dev/null
	done
	echo "done"
	exit 0
}

